apiVersion: v1
kind: Service
metadata:
  name: nodejs-dev
  labels:
    app.kubernetes.io/name: nodejs-dev
    app.kubernetes.io/managed-by: k8s-local
spec:
  selector:
    app.kubernetes.io/name: nodejs-dev
  ports:
    - name: http
      port: 3000
      targetPort: http